mailin:
  build: ./mailin
  ports:
   - "25:25"
  links:
   - tricket
  environment:
  - WEBHOOK=http://tricket:3000/api/emails
tricket:
  build: .
  ports:
   - "81:81"
  links:
    - mongo
  environment:
   - NODE_ENV=pro
  volumes:
    - ~/ses.js:/web/config/ses.js:ro
    - ~/auth.js:/web/config/auth.js:ro
mongo:
  image: mongo
backup:
  build: ./backup
  volumes:
    - ~/.aws:/root/.aws
  volumes_from:
    - tricket
  links:
    - mongo
migrate-up:
  build: .
  links:
    - mongo
  command: node ./node_modules/mongodb-migrate -runmm -cfg docker-config.json
