nginx:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - tricket
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ~/ondevio.com.key:/etc/nginx/ondevio.com.key:ro
    - ~/ondevio.com.chain.cert:/etc/nginx/ondevio.com.chain.cert:ro
mailin:
  build: ./mailin
  ports:
   - "25:25"
  links:
   - tricket
  environment:
  - WEBHOOK=http://tricket:3000/api/emails
tricket:
  build: .
  links:
    - mongo
    - backup
  environment:
   - NODE_ENV=pro
  volumes:
    - ~/ses.js:/web/config/ses.js:ro
    - ~/auth.js:/web/config/auth.js:ro
mongo:
  image: mongo
backup:
  build: ./backup
  volumes:
    - ~/.aws:/root/.aws
  links:
    - mongo
migrate-up:
  build: .
  links:
    - mongo
  command: node ./node_modules/mongodb-migrate -runmm -cfg docker-config.json
