mailin:
  build: ./mailin
  ports:
   - "25:25"
  links:
   - tricket 
  environment:
  - WEBHOOK=http://tricket.ondevio.com/emails
  hostname: tricket.ondevio.com
tricket:
  build: .
  ports:
   - "80:3000" 
